version: '3.8'
services:
  db:
    image: mysql
    container_name: produtoDbFaculdade
    restart: always
    environment:
      - MYSQL_DATABASE=produtoDB
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
